config/routes.rb
Rails.application.routes.draw do
  resources :notifications
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "login", to: redirect("/auth/google_oauth2"), as: "login"
  get "logout", to: "sessions#destroy", as: "logout"
  get "auth/:provider/callback", to: "sessions#create"
  get "auth/failure", to: redirect("/")
  root "home#index"
  get "home", to: "home#index"
  get "/show", to: "home#show"
  resources :users, except: [:show]
  resources :categories, except: [:show]
  resources :brands, except: [:show]
  resources :employees, except: [:show]
  resources :items do
    resources :posts
  end
  resources :storage, only: [:index]
  resources :issues, except: [:show]
  mount ActionCable.server => "/cable"
  get "notifications", to: "notifications#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :items
  validates :name, presence: { message: "must be given please" }
  validates :name, uniqueness: { message: "has been taken already" }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items, dependent: :destroy
  validates :name, presence: { message: "must be given please" }
  validates :name, uniqueness: { message: "has been taken already" }
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :items
  validates :name, presence: { message: "must be given please" }
  validates :name, uniqueness: { message: "has been taken already" }
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
end

app/models/issue.rb
class Issue < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :brand, optional: true
  belongs_to :category
  belongs_to :employee, optional: true

  has_many :posts, dependent: :destroy
  has_many :issues, dependent: :destroy

  validates :name, presence: { message: "must be given please" }
  validates :name, uniqueness: { message: "has been taken already" }
end

app/models/notification.rb
class Notification < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :item

  has_attached_file :image_or_pdf
  validates_attachment_content_type :image_or_pdf, content_type: ["image/jpeg", "image/png", "application/pdf", "application/msword"]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :issues
  validates :name, presence: { message: "must be given please" }
  validates :name, uniqueness: { message: "has been taken already" }
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate, except: :index

  def index; end

  def show; end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :get_issue, only: %i[edit update destroy]
  def index
    @issues = Issue.paginate(page: params[:page], per_page: 5)
  end

  def new
    @issue = Issue.new
  end

  def create
    @issue = Issue.new(issue_params)
    if @issue.save
      redirect_to issues_path, alert: "User created successfully."
    else
      render new_issue_path, alert: "Error creating issue."
    end
  end

  def edit; end

  def update
    if @issue.update(issue_params)
      UsersMailer.with(issue: @issue).Update(@issue).deliver_now if @issue.status == true
      redirect_to(issues_path(@issue), flash: { success: "Successfully Updated" })
    else
      render "edit"
    end
  end

  def destroy
    if @issue.destroy
      flash[:notice] = "Successfully deleted!"
      redirect_to issues_path
    else
      flash[:notice] = "Error deleting issue!"
    end
  end

  private

  def issue_params
    params.require(:issue).permit(:details, :item_id, :user_id, :status)
  end

  def get_issue
    @issue = Issue.find(params[:id])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :get_item, only: %i[show edit update destroy]
  def index
    @items = Item.includes(:employee).paginate(page: params[:page], per_page: 5)
  end

  def new
    @item = Item.new
    @post = @item.posts.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      @category = @item.category
      if @category.items.size <= @category.buffer && @category.items.size > @category.min_quan
        @notification = Notification.create(name: "Please, add some more!.", priority: false)
        ActionCable.server.broadcast "web_notifications_channel", notification: @notification.name, count: Notification.all.count
      end
      if @category.items.size <= @category.min_quan
        @notification = Notification.create(name: "Please, add more items as soon as possible.", priority: true)
        ActionCable.server.broadcast "web_notifications_channel", notification: @notification.name, count: Notification.all.count
      end
      unless params[:item][:post].blank?
        params[:item][:post]["image_or_pdf"].each do |img|
          @photo = @item.posts.create!(image_or_pdf: img)
        end
      end

      flash[:success] = "#{@item.name} is Created Successfully!"
      redirect_to items_path
    else
      render "new"
    end
  end

  def show
    @posts = @item.posts
  end

  def edit
    @item.posts.build unless @item.posts.any?
  end

  def update
    if (@item.status != item_params[:status]) && (@item.status == true)
      @category = @item.category
      count = @category.items.count
      count -= 1
      if count <= @category.buffer && count > @category.min_quan
        @notification = Notification.create(name: "Please, add some more!.", priority: false)
        ActionCable.server.broadcast "web_notifications_channel", notification: @notification.name, count: Notification.all.count
      end
      if count <= @category.min_quan
        @notification = Notification.create(name: "Please, add more items as soon as possible.", priority: true)
        ActionCable.server.broadcast "web_notifications_channel", notification: @notification.name, count: Notification.all.count
      end
    end
    if @item.update_attributes(item_params)
      if params[:item][:post].present?
        params[:item][:post]["image_or_pdf"].each do |img|
          @photo = @item.posts.create(image_or_pdf: img)
        end
      end

      flash[:success] = "#{@item.name} is Updated Successfully!"
      redirect_to items_path(@item)
    else
      render "edit"
    end
  end

  def destroy
    if @item.destroy
      flash[:notice] = "Successfully deleted!"
      redirect_to items_path
    else
      flash[:notice] = "Error deleting employee!"
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :brand_id, :category_id, :employee_id, :status, :notes, post_attributes: [:image_or_pdf])
  end

  def get_item
    @item = Item.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when "notice" then "alert alert-info"
    when "success" then "alert alert-success"
    when "error" then "alert alert-danger"
    when "alert" then "alert alert-warning"
    end
  end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/storage_helper.rb
module StorageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/issues/edit.html.erb
<%= render "shared/nav" %>
<div class="container">
  <%= bootstrap_form_for(@issue) do |f| %>
    <%= f.text_field :details, label: "Details :" %><br />
    <%= f.collection_select(:item_id, Item.all, :id, :name, {:prompt => "Select the item"} ) %><br />
    <%= f.check_box :status, label: "Solved?" %><br />
    <%= f.submit %>
  <% end %>
</div>

app/views/issues/index.html.erb
<%= render "shared/nav" %>
<div class="container">
  <h2>Issues</h2>

  <div class = "row">
      <div class = "col-sm-6">
        <%= will_paginate @issues,renderer: BootstrapPagination::Rails %>
      </div>
      <div class = "col-sm-6">
        <%= link_to ("Add"), new_issue_path, class: "btn btn-primary add" %>
      </div>
    </div>

  <% if @issues.present? %>

  <table class = "table table-bordered">
    <thead>
      <tr class="bg-info">
        <th>Issue ID</th>
        <th>Details</th>
        <th>Item</th>
        <th>User</th>
        <th>Status</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @issues.each do |issue| %>
        <tr>
          <td><%= issue.id %></td>
          <td><%= issue.details %></td>
          <td><%= issue.item.name %></td>
          <td><%= issue.user.name %></td>
          <% if issue.status==false %>
            <td>Not Solved</td>
          <% else %>
            <td>Solved</td>
          <% end %>
          <td>
            <% if issue.status == false %>
              <%= link_to ("<i class='fas fa-edit'></i>".html_safe), edit_issue_path(issue) %>
            <% end %>
          </td>
          <td><%= link_to "<i class='fas fa-backspace'></i>".html_safe, issue_path(issue), method: :delete, data: { confirm: "Are you sure?" } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <% else %>
    <h4>No issues yet!</h4>
  <% end %>

</div>

app/views/issues/new.html.erb
<%= render "shared/nav" %>
<div class="container">
  <%= bootstrap_form_for(@issue) do |f| %>
    <%= f.text_field :details, label: "Details :" %><br />
    <%= f.collection_select(:item_id, Item.all, :id, :name, {:prompt => "Select the item"} ) %><br />
    <%= f.collection_select(:user_id, User.all, :id, :name, {:prompt => "Select the iuser"} ) %><br />
    <%= f.check_box :status, label: "Solved?" %><br />
    <%= f.submit %>
  <% end %>
</div>