config/routes.rb
Rails.application.routes.draw do
  resources :notifications
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "login", to: redirect("/auth/google_oauth2"), as: "login"
  get "logout", to: "sessions#destroy", as: "logout"
  get "auth/:provider/callback", to: "sessions#create"
  get "auth/failure", to: redirect("/")
  root "home#index"
  get "home", to: "home#index"
  get "/show", to: "home#show"
  resources :users, except: [:show]
  resources :categories, except: [:show]
  resources :brands, except: [:show]
  resources :employees, except: [:show]
  resources :items do
    resources :posts
  end
  resources :storage, only: [:index]
  resources :issues, except: [:show]
  mount ActionCable.server => "/cable"
  get "notifications", to: "notifications#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :items
  validates :name, presence: { message: "must be given please" }
  validates :name, uniqueness: { message: "has been taken already" }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items, dependent: :destroy
  validates :name, presence: { message: "must be given please" }
  validates :name, uniqueness: { message: "has been taken already" }
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :items
  validates :name, presence: { message: "must be given please" }
  validates :name, uniqueness: { message: "has been taken already" }
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
end

app/models/issue.rb
class Issue < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :brand, optional: true
  belongs_to :category
  belongs_to :employee, optional: true

  has_many :posts, dependent: :destroy
  has_many :issues, dependent: :destroy

  validates :name, presence: { message: "must be given please" }
  validates :name, uniqueness: { message: "has been taken already" }
end

app/models/notification.rb
class Notification < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :item

  has_attached_file :image_or_pdf
  validates_attachment_content_type :image_or_pdf, content_type: ["image/jpeg", "image/png", "application/pdf", "application/msword"]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :issues
  validates :name, presence: { message: "must be given please" }
  validates :name, uniqueness: { message: "has been taken already" }
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when "notice" then "alert alert-info"
    when "success" then "alert alert-success"
    when "error" then "alert alert-danger"
    when "alert" then "alert alert-warning"
    end
  end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/storage_helper.rb
module StorageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Samagri</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="<%= flash_class(key) %>">
        <%= value %>
      </div>
    <% end %>

    

      <%= yield %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="panel panel-danger">
    <div class="panel-heading">
      <h5 class="panel-title">
        <%= pluralize(obj.errors.count, "error") %>
        prohibited this from being saved
      </h5>
      <div class="panel-body">
        <ul>
          <% obj.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_nav.html.erb
<div class="row">
  <div class="container-fluid space">
    <nav class="navbar navbar-expand-sm bg-dark">
      <%= link_to "Inventory", show_path, class: "navbar-brand logo" %>
      <div class="collapse navbar-collapse justify-content-end">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Users", users_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Categories", categories_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Brands", brands_path, class: "nav-link" %>
          </li>

          <!-- Dropdown -->
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
              More
            </a>
            <div class="dropdown-menu">
              <%= link_to "Employees", employees_path, class: "dropdown-item" %>
              <%= link_to "Items", items_path, class: "dropdown-item" %>
              <%= link_to "Issues", issues_path, class: "dropdown-item" %>
              <%= link_to "Storage", storage_index_path, class: "dropdown-item" %>
            </div>
          </li>

          <li class="nav-item dropdown">
            <% if current_user.is_admin? %>
              <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
                Notification (<b class="notifications-count">0</b>)
              </a>
              <div class="dropdown-menu" id="notification">
                <% Notification.all.each do |notification| %>
                  <a class="dropdown-item <%= notification.priority == true ? 'high_class' : 'low_class' %>" href="#"><%= notification.name %></a>
                <% end %>
              </div>
            <% end %>
          </li>

          <li class="nav-item dropdown">
          <a class="fas fa-user nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
            <%= current_user.name %>
          </a>
          <div class="dropdown-menu">
            <%= link_to "Logout", logout_path, class: "dropdown-item" %>
          </div>
        </li>
          
        </ul>
      </div>
    </nav>
  </div>
</div>