config/routes.rb
Rails.application.routes.draw do
  resources :notifications
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "login", to: redirect("/auth/google_oauth2"), as: "login"
  get "logout", to: "sessions#destroy", as: "logout"
  get "auth/:provider/callback", to: "sessions#create"
  get "auth/failure", to: redirect("/")
  root "home#index"
  get "home", to: "home#index"
  get "/show", to: "home#show"
  resources :users, except: [:show]
  resources :categories, except: [:show]
  resources :brands, except: [:show]
  resources :employees, except: [:show]
  resources :items do
    resources :posts
  end
  resources :storage, only: [:index]
  resources :issues, except: [:show]
  mount ActionCable.server => "/cable"
  get "notifications", to: "notifications#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :items
  validates :name, presence: { message: "must be given please" }
  validates :name, uniqueness: { message: "has been taken already" }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items, dependent: :destroy
  validates :name, presence: { message: "must be given please" }
  validates :name, uniqueness: { message: "has been taken already" }
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :items
  validates :name, presence: { message: "must be given please" }
  validates :name, uniqueness: { message: "has been taken already" }
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
end

app/models/issue.rb
class Issue < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :brand, optional: true
  belongs_to :category
  belongs_to :employee, optional: true

  has_many :posts, dependent: :destroy
  has_many :issues, dependent: :destroy

  validates :name, presence: { message: "must be given please" }
  validates :name, uniqueness: { message: "has been taken already" }
end

app/models/notification.rb
class Notification < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :item

  has_attached_file :image_or_pdf
  validates_attachment_content_type :image_or_pdf, content_type: ["image/jpeg", "image/png", "application/pdf", "application/msword"]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :issues
  validates :name, presence: { message: "must be given please" }
  validates :name, uniqueness: { message: "has been taken already" }
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate, except: :index

  def index; end

  def show; end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :get_item, only: %i[show edit update destroy]
  def index
    @items = Item.includes(:employee).paginate(page: params[:page], per_page: 5)
  end

  def new
    @item = Item.new
    @post = @item.posts.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      @category = @item.category
      if @category.items.size <= @category.buffer && @category.items.size > @category.min_quan
        @notification = Notification.create(name: "Please, add some more!.", priority: false)
        ActionCable.server.broadcast "web_notifications_channel", notification: @notification.name, count: Notification.all.count
      end
      if @category.items.size <= @category.min_quan
        @notification = Notification.create(name: "Please, add more items as soon as possible.", priority: true)
        ActionCable.server.broadcast "web_notifications_channel", notification: @notification.name, count: Notification.all.count
      end
      unless params[:item][:post].blank?
        params[:item][:post]["image_or_pdf"].each do |img|
          @photo = @item.posts.create!(image_or_pdf: img)
        end
      end

      flash[:success] = "#{@item.name} is Created Successfully!"
      redirect_to items_path
    else
      render "new"
    end
  end

  def show
    @posts = @item.posts
  end

  def edit
    @item.posts.build unless @item.posts.any?
  end

  def update
    if (@item.status != item_params[:status]) && (@item.status == true)
      @category = @item.category
      count = @category.items.count
      count -= 1
      if count <= @category.buffer && count > @category.min_quan
        @notification = Notification.create(name: "Please, add some more!.", priority: false)
        ActionCable.server.broadcast "web_notifications_channel", notification: @notification.name, count: Notification.all.count
      end
      if count <= @category.min_quan
        @notification = Notification.create(name: "Please, add more items as soon as possible.", priority: true)
        ActionCable.server.broadcast "web_notifications_channel", notification: @notification.name, count: Notification.all.count
      end
    end
    if @item.update_attributes(item_params)
      if params[:item][:post].present?
        params[:item][:post]["image_or_pdf"].each do |img|
          @photo = @item.posts.create(image_or_pdf: img)
        end
      end

      flash[:success] = "#{@item.name} is Updated Successfully!"
      redirect_to items_path(@item)
    else
      render "edit"
    end
  end

  def destroy
    if @item.destroy
      flash[:notice] = "Successfully deleted!"
      redirect_to items_path
    else
      flash[:notice] = "Error deleting employee!"
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :brand_id, :category_id, :employee_id, :status, :notes, post_attributes: [:image_or_pdf])
  end

  def get_item
    @item = Item.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def destroy
    @item = Item.find(params[:item_id])
    @post = Post.find(params[:id]).destroy
    redirect_to item_path(@item, @post)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when "notice" then "alert alert-info"
    when "success" then "alert alert-success"
    when "error" then "alert alert-danger"
    when "alert" then "alert alert-warning"
    end
  end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/storage_helper.rb
module StorageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/edit.html.erb
<%= render "shared/nav" %>

<div class="container">
<%= render "shared/errors", obj: @item %>
  <%= bootstrap_form_for(@item, html:{ multipart: true }) do |f| %>
    <%= f.text_field :name, label: "Name :" %><br />
    <%= f.collection_select(:brand_id, Brand.all, :id, :name, {:prompt => "Select the brand"}, :selected => @item.brand_id ) %><br />
    <%= f.collection_select(:category_id, Category.all, :id, :name, {:prompt => "Select the category"}, :selected => @item.category_id ) %>  <br />
    <% if !@item.employee.present? %>
      <%= f.collection_select(:employee_id, Employee.all.where(status: true), :id, :name, {:prompt => "Select the employee"}, :selected => @item.employee_id ) %><br />
    <% end %>
    <%= f.check_box :status, label: "Working?" %><br />
    <%= f.text_field :notes, label: "Notes :" %><br />
    <%= f.fields_for :post do |t| %>
      <%= t.label :attachment %>
      <% if @item.posts.size > 1 %>
        <% @item.posts.each do |post| %>
          <div>
            <%= image_tag post.image_or_pdf.url(:thumb) %>
          </div>
        <% end %>
        <%= t.file_field :image_or_pdf, accept: "image/jpeg,image/png,application/pdf,application/msword", multiple: true %>
      <% else %>
        <%= t.file_field :image_or_pdf, accept: "image/jpeg,image/png,application/pdf,application/msword", multiple: true %>
      <% end %>
    <% end %>
    
    <%= f.submit %>
  <% end %>
</div>

app/views/items/index.html.erb
<%= render "shared/nav" %>
<div class="container">
  <h2>Items</h2>

  <div class = "row">
      <div class = "col-sm-6">
        <%= will_paginate @items, renderer: BootstrapPagination::Rails %>
      </div>
      <div class = "col-sm-6">
        <% if current_user.is_admin == true %>
          <%= link_to ("Add"), new_item_path, class: "btn btn-primary add" %>
        <% end %>
      </div>
    </div>

  <table class = "table table-bordered">
    <thead>
      <tr class="bg-info">
        <th>ID</th>
        <th>Name</th>
        <th>Employee</th>
        <th>Status</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><%= link_to item.id, item_path(item) %></td>
          <td><%= link_to item.name, item_path(item) %></td>
          <td>
            <%  if item.employee.present? %>
              <%= link_to item.employee.name, employees_path %>
            <% end %>
          </td>
          <% if item.status==true %>
            <td>Working</td>
          <% else %>
            <td>Not Working</td>
          <% end %>
          <% if current_user.is_admin == true %>
            <td><%= link_to ("<i class='fas fa-edit'></i>".html_safe), edit_item_path(item) %></td>
            <% if !item.employee.present? %>
              <td><%= link_to "<i class='fas fa-backspace'></i>".html_safe, item_path(item), method: :delete, data: { confirm: "Are you sure?" } %></td>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/items/new.html.erb
<%= render "shared/nav" %>

<div class="container">
<%= render "shared/errors", obj: @item %>
  <%= bootstrap_form_for(@item, html:{ multipart: true }) do |f| %>
    <%= f.text_field :name, label: "Name :" %><br />
    <%= f.collection_select(:brand_id, Brand.all, :id, :name, {:prompt => "Select the brand"} ) %><br />
    <%= f.collection_select(:category_id, Category.all, :id, :name, {:prompt => "Select the category"} ) %>  <br />
    <%= f.collection_select(:employee_id, Employee.all.where(status: true), :id, :name, {:prompt => "Select the employee"} ) %><br />
    <%= f.check_box :status, label: "Working?" %><br />
    <%= f.text_field :notes, label: "Notes :" %><br />
    <%= f.fields_for :post do |t| %>
      <%= t.label :attachment %>
      <% if @item.posts.size > 1 %>
        <% @item.posts.each do |post| %>
          <div>
            <%= image_tag post.image_or_pdf.url(:thumb) %>
          </div>
        <% end %>
        <%= t.file_field :image_or_pdf, accept: "image/jpeg,image/png,application/pdf,application/msword", multiple: true %>
      <% else %>
        <%= t.file_field :image_or_pdf, accept: "image/jpeg,image/png,application/pdf,application/msword", multiple: true %>
      <% end %>
    <% end %>
    
    <%= f.submit %>
  <% end %>
</div>

app/views/items/show.html.erb
<%= render "shared/nav" %>
<div class="container align">
  <h5>Id : <%= @item.id %></h5>
  Name : <%= @item.name %>
  <br>
  <%  if @item.brand.present? %>
    Brand : <%= link_to @item.brand.name, brands_path(@item.brand_id) %>
  <% end %>
  <br>
  <%  if @item.category.present? %>
    Category : <%= link_to @item.category.name, categories_path(@item.category_id) %>
  <% end %>
  <br>
  <%  if @item.employee.present? %>
    Employee : <%= link_to @item.employee.name, employees_path(@item.employee_id) %>
  <% end %>
  <br>
  Status : <%= @item.status %><br>
  <%  if @item.notes.present? %>
    Notes : <%= @item.notes %>
  <% end %>
  <hr>

  <% if @item.posts.count > 0 %>
    <h5>Posts (<%= @item.posts.count %>)</h5>
    <% @item.posts.each do |post|  %>
        <%= link_to image_url(post.image_or_pdf.url) do%>
          <%= File.basename(post.image_or_pdf_file_name, ".*") %>
          <% if current_user.is_admin == true %>
            <%= link_to "<i class='fas fa-edit'></i>".html_safe, item_post_path(@item, post.id), 
              method: :delete, data: { confirm: "Are You sure?" } %>
          <% end %>
        <% end %>
        <hr>
        
      <% end %>
  <% end %>
</div>